In [207]:
import numpy as np

from bokeh.models import ColumnDataSource, DataRange1d, Plot, LinearAxis, Grid, Legend
from bokeh.plotting import figure
from bokeh.models.glyphs import Quad
from bokeh.io import curdoc, show, output_notebook
from bokeh.models.ranges import FactorRange
from bokeh.palettes import viridis
output_notebook()

Loading BokehJS ...

In [208]:
N = 9
x = np.linspace(-2, 2, N)
y = x**2

source = ColumnDataSource(dict(
        left=x,
        top=y,
        right=x-x**3/10 + 0.3,
        bottom=y-x**2/10 + 0.5,
    )
)

xdr = DataRange1d()
ydr = DataRange1d()

plot = Plot(
    title=None, x_range=xdr, y_range=ydr, plot_width=300, plot_height=300,
    h_symmetry=False, v_symmetry=False, min_border=0, toolbar_location=None)

glyph = Quad(left="left", right="right", top="top", bottom="bottom", fill_color="#b3de69")
plot.add_glyph(source, glyph)

xaxis = LinearAxis()
plot.add_layout(xaxis, 'below')

yaxis = LinearAxis()
plot.add_layout(yaxis, 'left')

plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))

curdoc().add_root(plot)

show(plot)

In [209]:
listEvntsName = ['EvntType1', 'EvntType2', 'EvnType3']
x = np.linspace(1,9,9,dtype='int')
evntStartTime = np.array([x**2, x**2 + 2, x**2 + 5])
evntEndTime = evntStartTime + np.random.randint(1,5,(3,9))

In [210]:
print (evntStartTime)
print (evntEndTime)

[[ 1  4  9 16 25 36 49 64 81]
 [ 3  6 11 18 27 38 51 66 83]
 [ 6  9 14 21 30 41 54 69 86]]
[[ 2  5 12 17 28 40 50 66 82]
 [ 6  7 14 19 30 40 52 68 86]
 [ 9 12 16 22 31 44 57 70 90]]


In [220]:
plot_width = 900
plot_height = 90

In [221]:
xdr = DataRange1d()
ydr = DataRange1d()

In [222]:
legends = ['asd','bsd']

In [223]:
source0 = ColumnDataSource(dict(
        left=evntStartTime[0],
        right=evntEndTime[0],
        top = [1] * len(evntStartTime[0]),
        bottom = [0] * len(evntStartTime[0])
    )
)

In [224]:
source1 = ColumnDataSource(dict(
        left=evntStartTime[1],
        right=evntEndTime[1],
        top = [2] * len(evntStartTime[0]),
        bottom = [1] * len(evntStartTime[0]) 
    )
)

In [227]:
plot = figure(
    title=None, x_range=xdr, y_range=ydr, plot_width=plot_width, plot_height=plot_height,
    h_symmetry=False, v_symmetry=False, min_border=0)

glyph0 = plot.quad(left="left", right="right", top="top", bottom="bottom",fill_color=colors[0],source=source0)#,legend='asd')
glyph1 = plot.quad(left="left", right="right", top="top", bottom="bottom",fill_color=colors[1],source=source1)#,legend='bsd')

legend = Legend(items=[
                    ("asd",[glyph0]),
                    ("bsd",[glyph1])],
                location=(30, 0))
    
plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))

plot.add_layout(legend, 'right')

show(plot)