In [1]:
# Exer 1
import numpy as np
np.__version__sion__

'1.14.0'

In [3]:
# Exer 2
print (np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# Exer 3
print (np.array ([[True]*3]*3))

# From site
print (np.full((3, 3), True, dtype=bool))
# Alternate method:
np.ones((3,3), dtype=bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
# Q. Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print (arr[arr%2 != 0])

[1 3 5 7 9]


In [10]:
# Replace all odd numbers in arr with -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2 != 0] = -1
print (arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [12]:
# Q. Replace all odd numbers in arr with -1 without changing arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = np.copy(arr)
out[out%2 != 0] = -1
print (out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
# Q. Convert a 1D array to a 2D array with 2 rows

asd = np.arange(10)

asd.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
# Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print (np.concatenate((a,b),axis = 1))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
