In [1]:
import numpy as np

#### Append

In [2]:
asd = np.arange(24).reshape(2,3,4)

In [3]:
print (asd)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
bsd = np.append(asd, [5,6,7,8])

In [5]:
print (bsd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  5  6  7  8]


In [7]:
# Append creates a new array
print (asd is bsd)

False


In [9]:
print (bsd.reshape(7,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 5  6  7  8]]


In [10]:
csd = np.arange(24).reshape(2,3,4) * 10 +1

In [11]:
print (np.append(asd,csd))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23   1  11  21  31  41  51  61  71  81  91 101 111
 121 131 141 151 161 171 181 191 201 211 221 231]


In [13]:
print (np.append(asd,csd, axis=0).shape)

(4, 3, 4)


In [15]:
print (np.append(asd,csd, axis=1).shape)

(2, 6, 4)


In [17]:
print (np.append(asd,csd, axis=2).shape)

(2, 3, 8)


### Hstack

In [19]:
print (np.hstack((asd, csd)).shape)

(2, 6, 4)


In [20]:
print (np.vstack((asd, csd)).shape)

(4, 3, 4)


### Insert

In [21]:
print (np.insert(asd,1,444,axis=0))

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[444 444 444 444]
  [444 444 444 444]
  [444 444 444 444]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


In [22]:
print (np.insert(asd,1,444,axis=1))

[[[  0   1   2   3]
  [444 444 444 444]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [444 444 444 444]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


In [23]:
print (np.insert(asd,1,444,axis=2))

[[[  0 444   1   2   3]
  [  4 444   5   6   7]
  [  8 444   9  10  11]]

 [[ 12 444  13  14  15]
  [ 16 444  17  18  19]
  [ 20 444  21  22  23]]]


### Delete

In [25]:
print (np.delete(asd, 1, axis=0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [26]:
print (np.delete(asd, 1, axis=1))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]


In [27]:
print (np.delete(asd, 1, axis=2))

[[[ 0  2  3]
  [ 4  6  7]
  [ 8 10 11]]

 [[12 14 15]
  [16 18 19]
  [20 22 23]]]
