### Two dim arrays

In [1]:
import numpy as np

In [2]:
asd = np.arange(35)

In [3]:
print (asd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


In [5]:
asd.shape = (5,7)

In [6]:
print (asd)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [7]:
print (asd.shape[0])

5


### Three dim array

In [8]:
bsd = np.arange(70)

In [10]:
print (bsd.reshape([2,5,7]))

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]]

 [[35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]]]


In [11]:
print (bsd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [12]:
bsd.shape = (2,5,7)

In [13]:
print (bsd)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]]

 [[35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]]]


In [17]:
print (bsd[0,:,:])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [18]:
print (bsd[0])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [19]:
print (bsd [-1])

[[35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]


In [21]:
print (bsd[1,2])

[49 50 51 52 53 54 55]


### Boolean Masks

In [29]:
asd = np.arange(1,11)

In [30]:
print (asd [asd %2 == 0])

[ 2  4  6  8 10]


In [31]:
print (asd)

[ 1  2  3  4  5  6  7  8  9 10]


### Broadcasting

In [32]:
print (bsd)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]]

 [[35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]]]


In [33]:
print (bsd.shape)

(2, 5, 7)


In [34]:
print (bsd.ndim)

3


In [35]:
print (bsd.size)

70


In [36]:
print (bsd.dtype)

int64


In [37]:
print (bsd.sum())

2415


In [38]:
print (bsd.sum(axis=0))

[[ 35  37  39  41  43  45  47]
 [ 49  51  53  55  57  59  61]
 [ 63  65  67  69  71  73  75]
 [ 77  79  81  83  85  87  89]
 [ 91  93  95  97  99 101 103]]
