### Two dim arrays

In [1]:
import numpy as np

In [2]:
asd = np.arange(35)

In [3]:
print (asd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


In [4]:
asd.shape = (5,7)

In [5]:
print (asd)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [6]:
print (asd.shape[0])

5


### Three dim array

In [7]:
bsd = np.arange(70)

In [8]:
print (bsd.reshape([2,5,7]))

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]]

 [[35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]]]


In [9]:
print (bsd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [10]:
bsd.shape = (2,5,7)

In [11]:
print (bsd)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]]

 [[35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]]]


In [12]:
print (bsd[0,:,:])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [13]:
print (bsd[0])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [14]:
print (bsd [-1])

[[35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]


In [15]:
print (bsd[1,2])

[49 50 51 52 53 54 55]


### Boolean Masks

In [16]:
asd = np.arange(1,11)

In [17]:
print (asd [asd %2 == 0])

[ 2  4  6  8 10]


In [18]:
print (asd)

[ 1  2  3  4  5  6  7  8  9 10]


### Sum with Axis

In [29]:
bsd = np.arange(30).reshape((2,3,5))
print (bsd)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [30]:
print (bsd.shape)

(2, 3, 5)


In [31]:
print (bsd.ndim)

3


In [32]:
print (bsd.size)

30


In [33]:
print (bsd.dtype)

int64


In [34]:
print (bsd.sum())

435


In [38]:
print (bsd.sum(axis=0))
print (bsd.sum(axis=0).shape)

[[15 17 19 21 23]
 [25 27 29 31 33]
 [35 37 39 41 43]]
(3, 5)


In [39]:
print (bsd.sum(axis=1))
print (bsd.sum(axis=1).shape)

[[15 18 21 24 27]
 [60 63 66 69 72]]
(2, 5)


In [40]:
print (bsd.sum(axis=2))
print (bsd.sum(axis=2).shape)

[[ 10  35  60]
 [ 85 110 135]]
(2, 3)


If we gives (axis = 0), it eliminates 0th axis and results in matrix (3,5) i.e. it sums over "channel" axis. 
In case (axis = 1), it sums over "rows" axis i.e. find the sum of rows in each channel. It eliminates 1st axis and resulting shape is (2,5) 
In case of axis=2, it sums over elements in the rows and results in size of (2,3) 
