### Joining arrays

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])

In [16]:
b = np.array([[5,6]])

In [17]:
print (a,b)

[[1 2]
 [3 4]] [[5 6]]


In [18]:
# a and b must have same number of dimensions
print (np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [20]:
# a and b must have same number of dimensions
print (np.concatenate((a,np.transpose(b)),axis=1))

[[1 2 5]
 [3 4 6]]


### Split arrays

In [23]:
asd = np.random.rand(5,3,4)

In [24]:
print (asd)

[[[0.61075269 0.80042889 0.2767181  0.16687219]
  [0.97486178 0.37867358 0.22769131 0.63876584]
  [0.55096412 0.21752153 0.65496944 0.61841462]]

 [[0.64232649 0.60514485 0.36476673 0.92897845]
  [0.22613093 0.07259844 0.78406556 0.30495108]
  [0.88770519 0.21585426 0.72284245 0.41081143]]

 [[0.21882728 0.80702457 0.14366117 0.69747161]
  [0.05043215 0.43875884 0.47904258 0.71692004]
  [0.94505698 0.40632352 0.60304002 0.61858829]]

 [[0.25585692 0.80261645 0.42973455 0.99359422]
  [0.4113702  0.28629624 0.85361556 0.63564603]
  [0.13299261 0.43568376 0.45448585 0.49269536]]

 [[0.01155461 0.94826245 0.80541192 0.77861574]
  [0.80324033 0.2120087  0.32551079 0.46635679]
  [0.8061555  0.27284158 0.07398847 0.67617713]]]


In [33]:
bsd = np.split(asd,5,axis=0)

print (bsd)

print (len(bsd), bsd[0].shape)

[array([[[0.61075269, 0.80042889, 0.2767181 , 0.16687219],
        [0.97486178, 0.37867358, 0.22769131, 0.63876584],
        [0.55096412, 0.21752153, 0.65496944, 0.61841462]]]), array([[[0.64232649, 0.60514485, 0.36476673, 0.92897845],
        [0.22613093, 0.07259844, 0.78406556, 0.30495108],
        [0.88770519, 0.21585426, 0.72284245, 0.41081143]]]), array([[[0.21882728, 0.80702457, 0.14366117, 0.69747161],
        [0.05043215, 0.43875884, 0.47904258, 0.71692004],
        [0.94505698, 0.40632352, 0.60304002, 0.61858829]]]), array([[[0.25585692, 0.80261645, 0.42973455, 0.99359422],
        [0.4113702 , 0.28629624, 0.85361556, 0.63564603],
        [0.13299261, 0.43568376, 0.45448585, 0.49269536]]]), array([[[0.01155461, 0.94826245, 0.80541192, 0.77861574],
        [0.80324033, 0.2120087 , 0.32551079, 0.46635679],
        [0.8061555 , 0.27284158, 0.07398847, 0.67617713]]])]
5 (1, 3, 4)


In [34]:
csd = np.split(asd,2,axis=2)

In [35]:
print (len(csd), csd[0].shape)

2 (5, 3, 2)
