In [1]:
import numpy as np

In [10]:
asd = np.arange(0,12,2)

In [16]:
print (asd)

[ 0  2  4  6  8 10]


### linspace()

In [12]:
bsd = np.linspace(1,10,20)

In [19]:
print (bsd)
print (bsd.size)
print (bsd.shape)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
20
(20,)


In [29]:
print (np.linspace(0,90,10))

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


#### zeros()

In [30]:
print (np.zeros([3]))

[0. 0. 0.]


In [31]:
print (np.zeros([2,3],dtype=np.int64))

[[0 0 0]
 [0 0 0]]
