<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [1]:
import numpy as np

In [2]:
arange(7)

NameError: name 'arange' is not defined

In [3]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
np.arange(10, 23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [5]:
np.arange(10, 23) -10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
np.arange(10, 23) -10 +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [7]:
len (np.arange(10, 23))

13

In [8]:
my_range_array = np.arange(10, 23)
my_range_array.size

13

In [9]:
np.arange(10, 23).size

13

In [10]:
np.arange(10, 23, 5)

array([10, 15, 20])

In [11]:
np.arange(10, 25, 5)

array([10, 15, 20])

In [12]:
np.arange(10, 26, 5)

array([10, 15, 20, 25])

In [13]:
np.arange(26, step=5)

array([ 0,  5, 10, 15, 20, 25])

In [14]:
np.arange(0, 26, step=5)

array([ 0,  5, 10, 15, 20, 25])

In [15]:
np.arange(0, 26, 5)

array([ 0,  5, 10, 15, 20, 25])

In [17]:
np.arange(10,18,step=2)

array([10, 12, 14, 16])