In [35]:
import pandas as pd

from bokeh.io import output_notebook, show
from bokeh.models import BasicTicker, ColorBar, ColumnDataSource, LinearColorMapper, PrintfTickFormatter
from bokeh.plotting import figure
from bokeh.sampledata.unemployment1948 import data
from bokeh.transform import transform
import numpy as np
from bokeh.models.ranges import FactorRange, DataRange1d
from bokeh.models import Plot
from bokeh.models.glyphs import Rect

output_notebook()

Loading BokehJS ...

In [36]:
data.Year = data.Year.astype(str)
data = data.set_index('Year')
data.drop('Annual', axis=1, inplace=True)
data.columns.name = 'Month'

# reshape to 1D array or rates with a month and year for each row.
df = pd.DataFrame(data.stack(), columns=['rate']).reset_index()

source = ColumnDataSource(df)

# this is the colormap from the original NYTimes plot
colors = ["#75968f", "#a5bab7", "#c9d9d3", "#e2e2e2", "#dfccce", "#ddb7b1", "#cc7878", "#933b41", "#550b1d"]
mapper = LinearColorMapper(palette=colors, low=df.rate.min(), high=df.rate.max())

p = figure(plot_width=800, plot_height=300, title="US Unemployment 1948—2016",
           x_range=list(data.index), y_range=list(reversed(data.columns)),
           toolbar_location=None, tools="", x_axis_location="above")

p.rect(x="Year", y="Month", width=1, height=1, source=source,
       line_color=None, fill_color=transform('rate', mapper))

color_bar = ColorBar(color_mapper=mapper, location=(0, 0),
                     ticker=BasicTicker(desired_num_ticks=len(colors)),
                     formatter=PrintfTickFormatter(format="%d%%"))

p.add_layout(color_bar, 'right')

p.axis.axis_line_color = None
p.axis.major_tick_line_color = None
p.axis.major_label_text_font_size = "5pt"
p.axis.major_label_standoff = 0
p.xaxis.major_label_orientation = 1.0

show(p)

In [37]:
listEvntsName = ['EvntType1', 'EvntType2', 'EvnType3']
x = np.linspace(1,9,9,dtype='int')
evntStartTime = np.array([x**2, x**2 + 2, x**2 + 5])
evntEndTime = evntStartTime + np.random.randint(1,5,(3,9))

In [38]:
print (evntStartTime)
print (evntEndTime)

[[ 1  4  9 16 25 36 49 64 81]
 [ 3  6 11 18 27 38 51 66 83]
 [ 6  9 14 21 30 41 54 69 86]]
[[ 4  7 11 20 28 37 51 66 82]
 [ 7  9 14 21 30 40 53 68 84]
 [ 8 12 17 24 31 45 55 72 87]]


In [39]:
plot_width = 700
plot_height = 70

In [40]:
xdr = DataRange1d()
ydr = FactorRange(listEvntsName)

In [50]:
source0 = ColumnDataSource(dict(
        left=evntStartTime[0],
        right=['EnvtType1'] * len(evntStartTime[0]),
        top = [1] * len(evntStartTime[0]),
        bottom = [0] * len(evntStartTime[0]) 
    )
)

In [51]:
plot = Plot(
    title=None, x_range=xdr, y_range=ydr, plot_width=plot_width, plot_height=plot_height,
    h_symmetry=False, v_symmetry=False, min_border=0, toolbar_location=None)

In [55]:
glyph0 = Rect(x= "left", y="right", width=1, height=1, line_color=None,  fill_color=colors[0])

In [56]:
plot.add_glyph(source0, glyph0)

GlyphRenderer(id='12ba01ef-26a4-40bf-9e5b-443afd3cf987', ...)

In [57]:
show(plot)

ERROR:/home/ankdesh/virtualenvs/bokeh/lib/python3.5/site-packages/bokeh/core/validation/check.py:E-1009 (INCOMPATIBLE_SCALE_AND_RANGE): A Scale is incompatible with one or more ranges on the same plot dimension: incompatibility on y-dimension: FactorRange(id='dfb4a7ce-22c2-495a-b67f-0fdf578efaf5', ...)/LinearScale(id='89f52e69-49ea-478e-b84d-8c5e3ea0f1f6', ...) [Plot(id='b5d4297a-76f0-42d3-87ab-3b9a5530af35', ...)]
