<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [2]:
import numpy as np

In [3]:
np.linspace(5, 15, 9)

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [4]:
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace[1]

1.25

In [5]:
np.linspace(5, 15, 9, retstep=True)[1]

1.25

<h2>zeros()</h2>

In [6]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [7]:
np.zeros((5, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

<h2>ones()</h2>

In [8]:
np.ones(7)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
np.ones((7, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

<h2>NumPy data types()</h2>

In [10]:
np.ones(11, dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [11]:
my_zeros = np.zeros((11, 15), dtype='int32')
my_zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
my_zeros.size

165

In [13]:
my_zeros.shape

(11, 15)

In [14]:
my_zeros.dtype

dtype('int32')

In [15]:
np.ones(11, dtype='float_')

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
np.zeros(11)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])