<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [1]:
import numpy as np

In [3]:
np.linspace(5, 15, 9)

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [2]:
my_linspace = np.linspace(5, 15, 9, retstep=True)
print(my_linspace)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)


In [3]:
np.linspace(5, 15, 9, retstep=True)[1]

1.25

In [5]:
print (np.linspace(0,1,10,retstep=True))

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]), 0.1111111111111111)


<h2>zeros()</h2>

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<h2>ones()</h2>

In [8]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((7, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
asd = np.zeros((10,5,2))
asd [3,:,:] = 1000
print (asd)

[[[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[1000. 1000.]
  [1000. 1000.]
  [1000. 1000.]
  [1000. 1000.]
  [1000. 1000.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]

 [[   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]
  [   0.    0.]]]


<h2>NumPy data types()</h2>

In [17]:
np.ones(11, dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
my_zeros = np.zeros((11, 15), dtype='int32')
my_zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [19]:
my_zeros.size

165

In [20]:
my_zeros.shape

(11, 15)

In [21]:
my_zeros.dtype

dtype('int32')

In [22]:
np.ones(11, dtype='float_')

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])